language: php

language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer remove --no-update --dev friendsofphp/php-cs-fixer
  - composer install --prefer-dist

script: vendor/bin/phpunit

